In [1]:
import numpy as np
from scipy.spatial.distance import dice

In [2]:
expected = np.array([
    [1, 1],
    [1, 0],
])

In [3]:
def compare(given):
    given = np.array(given)
    dice_coefficient = 1.0 - dice(given.reshape(4), expected.reshape(4))
    print(expected)
    print(given)
    print(f'Dice coefficient: {dice_coefficient}')
    print('-' * 40)

In [4]:
print('-' * 40)

compare([
    [1, 1],
    [1, 0],
])
compare([
    [0, 0],
    [0, 1],
])
compare([
    [1, 1],
    [0, 0],
])
compare([
    [1, 0],
    [1, 0],
])
compare([
    [1, 0],
    [0, 0],
])

----------------------------------------
[[1 1]
 [1 0]]
[[1 1]
 [1 0]]
Dice coefficient: 1.0
----------------------------------------
[[1 1]
 [1 0]]
[[0 0]
 [0 1]]
Dice coefficient: 0.0
----------------------------------------
[[1 1]
 [1 0]]
[[1 1]
 [0 0]]
Dice coefficient: 0.8
----------------------------------------
[[1 1]
 [1 0]]
[[1 0]
 [1 0]]
Dice coefficient: 0.8
----------------------------------------
[[1 1]
 [1 0]]
[[1 0]
 [0 0]]
Dice coefficient: 0.5
----------------------------------------
